name: Build and deploy (Hugo + Pages)

on:
  push:
    branches: ["root"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.148.2"
          extended: true

      - uses: actions/configure-pages@v5

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir --baseURL "https://lkmgit.github.io/"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
